### ISSUE TITLE
Check why some services stay ✖

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-devrun/is-epfl-down#50]
These services are not checked properly:
* vpn
* ewa
* cadiwww
* my (probably due to timeout)

**Comment by williambelle** [comment]
For cadiwww, I get a 403:

```
{ HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: 'cadiwww.epfl.ch',
  hostname: 'cadiwww.epfl.ch',
  method: 'HEAD',
  path: '/',
  protocol: 'http:',
  url: 'http://cadiwww.epfl.ch/',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers:
   { date: 'Thu, 10 Aug 2017 16:33:06 GMT',
     server: 'Apache/2.2.15 (Red Hat)',
     'last-modified': 'Fri, 07 Jul 2017 10:34:04 GMT',
     etag: '"20006-f91-553b7c5ab1f00"',
     'accept-ranges': 'bytes',
     'content-length': '3985',
     connection: 'close',
     'content-type': 'text/html; charset=UTF-8',
     'strict-transport-security': 'max-age=31536000' } }
```

As well as with the browser (https://cadiwww.epfl.ch/).

**Comment by williambelle** [comment]
With ewa:

```
{ HTTPError: Response code 440 (undefined)
    at stream.catch.then.data (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: 'ewa.epfl.ch',
  hostname: 'ewa.epfl.ch',
  method: 'HEAD',
  path: '/',
  protocol: 'http:',
  url: 'http://ewa.epfl.ch/',
  statusCode: 440,
  statusMessage: undefined,
  headers:
   { 'content-length': '43',
     'content-type': 'text/html; charset=utf-8',
     server: 'Microsoft-IIS/8.5',
     'request-id': 'be688160-87d7-4531-8953-df7d44c345a5',
     'set-cookie': [ 'ClientId=KSZPFNWCEVKAAVHLROA; expires=Fri, 10-Aug-2018 17:42:03 GMT; path=/; HttpOnly' ],
     'x-powered-by': 'ASP.NET',
     'x-feserver': 'EWA2',
     date: 'Thu, 10 Aug 2017 17:42:02 GMT',
     connection: 'close' } }
```

meaning 440 Login Timeout (Microsoft)

**Comment by williambelle** [comment]
With my:

```
{ MaxRedirectsError: Redirected 10 times. Aborting.
    at ClientRequest.fn.request.res (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:69:23)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
  name: 'MaxRedirectsError',
  host: 'tequila.epfl.ch',
  hostname: 'tequila.epfl.ch',
  method: 'HEAD',
  path: '/cgi-bin/tequila/requestauth?requestkey=om073a4hl0iz2l7toopozvzd4foyfpsn',
  protocol: 'https:',
  url: 'https://tequila.epfl.ch/cgi-bin/tequila/requestauth?requestkey=om073a4hl0iz2l7toopozvzd4foyfpsn',
  statusCode: 302,
  statusMessage: 'Found',
  redirectUrls:
   [ 'https://my.epfl.ch/',
     'https://my.epfl.ch/render.userLayoutRootNode.uP',
     'https://my.epfl.ch/Login?refUrl=%2Frender.userLayoutRootNode.uP',
     'https://tequila.epfl.ch/cgi-bin/tequila/requestauth?requestkey=dvks8vnrzbrb7x8st3cisc8fahiz5k41',
     'https://my.epfl.ch/Login?refUrl=%2Frender.userLayoutRootNode.uP&key=dvks8vnrzbrb7x8st3cisc8fahiz5k41',
     'https://tequila.epfl.ch/cgi-bin/tequila/requestauth?requestkey=ygbgi7l1szfj7lry08k6pg37r23stpvb',
     'https://my.epfl.ch/Login?refUrl=%2Frender.userLayoutRootNode.uP&key=dvks8vnrzbrb7x8st3cisc8fahiz5k41&key=ygbgi7l1szfj7lry08k6pg37r23stpvb',
     'https://tequila.epfl.ch/cgi-bin/tequila/requestauth?requestkey=btzmw8o7ehqlhhixo84gabdsq1bbfz71',
     'https://my.epfl.ch/Login?refUrl=%2Frender.userLayoutRootNode.uP&key=dvks8vnrzbrb7x8st3cisc8fahiz5k41&key=ygbgi7l1szfj7lry08k6pg37r23stpvb&key=btzmw8o7ehqlhhixo84gabdsq1bbfz71',
     'https://tequila.epfl.ch/cgi-bin/tequila/requestauth?requestkey=om073a4hl0iz2l7toopozvzd4foyfpsn' ] }
```

and I don't no why.

**Comment by williambelle** [comment]
With vpn:

```
{ RequestError: Request timed out
    at timeoutFn (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:131:53)
    at asPromise (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:134:9)
    at got (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:386:10)
    at Function.got.(anonymous function) [as head] (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:404:31)
    at testSubDomain (/Users/william/Documents/git/is-epfl-down/src/index.js:31:21)
    at module.exports (/Users/william/Documents/git/is-epfl-down/src/index.js:50:5)
    at Object.<anonymous> (/Users/william/Documents/git/is-epfl-down/src/cli.js:138:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'vpn.epfl.ch',
  hostname: 'vpn.epfl.ch',
  method: 'HEAD',
  path: '/',
  protocol: 'http:',
  url: 'http://vpn.epfl.ch/'
```

but http is not available. https:

```
{ HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/Users/william/Documents/git/is-epfl-down/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: 'vpn.epfl.ch',
  hostname: 'vpn.epfl.ch',
  method: 'HEAD',
  path: '/',
  protocol: 'https:',
  url: 'https://vpn.epfl.ch/',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers:
   { 'cache-control': 'no-cache',
     pragma: 'no-cache',
     connection: 'Close',
     date: 'Thu, 10 Aug 2017 18:02:46 GMT',
     'x-frame-options': 'SAMEORIGIN' } }
```

**Comment by williambelle** [comment]
@obieler Any ideas on how to improve ?
